import type { Context } from '@deepseek-ai/cordis';
import type { ChannelFactory, ResolvedConfig } from './types.js';
/** Bidirectional adapter between the official Lark Channel API and native Harness agents. */
export declare class LarkBridge {
    private readonly ctx;
    private readonly config;
    private readonly channel;
    private readonly state;
    private readonly sessions;
    private readonly creating;
    private readonly agents;
    private readonly pendingApprovals;
    private readonly pendingQuestions;
    private readonly selectedProjects;
    private headers;
    private disposers;
    private questionProviderDisposer?;
    private connected;
    private stopped;
    constructor(ctx: Context, config: ResolvedConfig, channelFactory?: ChannelFactory);
    private isGloballyAllowed;
    private isAuthorizedAction;
    private projectForMessage;
    private canUseProject;
    private availableProjects;
    private ensureGroupBinding;
    private shouldReplyInThread;
    start(): Promise<void>;
    private sendPendingWelcomes;
    stop(): Promise<void>;
    private registerQuestionProvider;
    private onMessage;
    private handleClaim;
    private handleBind;
    private handleUnbind;
    private inboundContent;
    private handleCommand;
    private ensureSession;
    private createSession;
    private modelSelection;
    private setupAgent;
    private nextSessionId;
    private rememberHeader;
    private rotateSession;
    private resumeSession;
    private onSessionEvent;
    private scheduleProgress;
    private upsertTurnCard;
    private enqueue;
    private replyOptions;
    private sendStatus;
    private askApproval;
    private settleApproval;
    private askQuestions;
    private askOneQuestion;
    private settleQuestion;
    private rejectQuestion;
    private onCardAction;
    private handleQuestionAction;
    private onReaction;
    private safeSend;
}
